---
abstract: 'Bringing loggers and listeners together'
author:
  - 'Jonathan Swartz <swartz@pobox.com>'
  - 'David Golden <dagolden@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
  File::Spec: '0'
  File::Temp: '0'
  Test::More: '0'
  perl: '5.008001'
configure_requires:
  ExtUtils::MakeMaker: '6.17'
  perl: '5.008001'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.029, CPAN::Meta::Converter version 2.142690'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Log-Any
no_index:
  directory:
    - t
    - xt
    - examples
    - corpus
  package:
    - DB
    - Log::Any::Manager::_Guard
provides:
  Log::Any:
    file: lib/Log/Any.pm
    version: '1.00'
  Log::Any::Adapter:
    file: lib/Log/Any/Adapter.pm
    version: '1.00'
  Log::Any::Adapter::Base:
    file: lib/Log/Any/Adapter/Base.pm
    version: '1.00'
  Log::Any::Adapter::File:
    file: lib/Log/Any/Adapter/File.pm
    version: '1.00'
  Log::Any::Adapter::Null:
    file: lib/Log/Any/Adapter/Null.pm
    version: '1.00'
  Log::Any::Adapter::Stderr:
    file: lib/Log/Any/Adapter/Stderr.pm
    version: '1.00'
  Log::Any::Adapter::Stdout:
    file: lib/Log/Any/Adapter/Stdout.pm
    version: '1.00'
  Log::Any::Adapter::Test:
    file: lib/Log/Any/Adapter/Test.pm
    version: '1.00'
  Log::Any::Adapter::Util:
    file: lib/Log/Any/Adapter/Util.pm
    version: '1.00'
  Log::Any::Manager:
    file: lib/Log/Any/Manager.pm
    version: '1.00'
  Log::Any::Proxy:
    file: lib/Log/Any/Proxy.pm
    version: '1.00'
  Log::Any::Proxy::Test:
    file: lib/Log/Any/Proxy/Test.pm
    version: '1.00'
  Log::Any::Test:
    file: lib/Log/Any/Test.pm
    version: '1.00'
requires:
  B: '0'
  Carp: '0'
  Data::Dumper: '0'
  Exporter: '0'
  Fcntl: '0'
  IO::File: '0'
  Test::Builder: '0'
  base: '0'
  constant: '0'
  perl: '5.008001'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/dagolden/Log-Any/issues
  homepage: https://github.com/dagolden/Log-Any
  repository: https://github.com/dagolden/Log-Any.git
version: '1.00'
x_authority: cpan:JSWARTZ
x_contributors:
  - 'Maxim Vuets <maxim.vuets@booking.com>'
  - 'Stephen Thirlwall <sdt@dr.com>'
