---
abstract: 'Bringing loggers and listeners together'
author:
  - 'Jonathan Swartz <swartz@pobox.com>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300028, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Log-Any
no_index:
  file:
    - lib/Log/Any/Adapter/Core.pm
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Log-Any
  repository: git://github.com/jonswar/perl-log-any.git
version: 0.15
